### ISSUE TITLE
Feature request: 'My blocks' have a return value

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-blocks#2101] opened 2020-08-20 00:38 UTC
Like in the title so it is an actual function. I do not know anything about JS.

**Comment by BryceLTaylor** [comment] 2020-08-20 18:38
This is a duplicate of https://github.com/LLK/scratch-vm/issues/1064 and https://github.com/LLK/scratch-vm/issues/79

**Closed as completed by BryceLTaylor** 2020-08-20 18:38 UTC
