### ISSUE TITLE
Please allow translations of sprites and backdrops

### ISSUE THREAD

**Issue by guyhed** [LLK/scratch-blocks#1851] opened 2019-01-03 13:23 UTC
The sprites in the "choose sprite" menu should appear in the child's native language.
In Israel most children below the 5th grade do not know English well enough to work with English names.

Please allow translation of the backdrops and sprites names.

**Comment by chrisgarrity** [comment] 2019-01-03 21:27
Duplicate of https://github.com/LLK/scratch-gui/issues/491

**Closed as completed** 2019-01-03 21:27 UTC
Labels: localization, request
