### ISSUE TITLE
Variables with old name reappear when renamed after switching sprites

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1216] opened 2017-11-08 21:59 UTC
### Expected Behavior

Renamed variable should stay renamed

### Actual Behavior

There are now 2 variables, one with the old name

### Steps to Reproduce

1. Go to Data. Create a variable.
2. Drag one of the data blocks to the workspace
2. Add a new sprite
3. Drag "set x to" block to workspace
4. In the dropdown, rename variable. Choose a new name
You can also rename variables by right clicking on them in the flyout and choosing rename

all appears well

5. Return to the first sprite
New variable with old name has appeared

### Operating System and Browser

Windows 10 chrome

**Comment by rachel-fenichel** [comment] 2017-11-08 22:03
Dupe of https://github.com/LLK/scratch-blocks/issues/1183

The fact that it occurs on sprite switch is a result of how scratch-gui uses scratch-blocks, but doesn't make it a different bug.

**Closed as completed by rachel-fenichel** 2017-11-08 22:03 UTC
