### ISSUE TITLE
Block deletion behavior

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#675] opened 2016-10-11 20:58 UTC
- Should the block animate out when you delete it? If so, where should it animate to? Should we try to replicate Blockly functionality on this? Seemed to be a little unclear what we wanted.
- Are we taking out the trash, or keeping it in?

**Comment by TheBrokenRail** [comment] 2016-10-13 01:58
I like the animation.

**Comment by tmickel** [comment] 2016-10-31 20:04
@carljbowman This is on the list for the prototype, fyi.

**Comment by carljbowman** [comment] 2016-12-12 20:51
We should keep the current animation. 

The trash can icon should be toggle-able, but by default is set to false. I worry that with zoom controls and in some cases (like our tablet prototype) including Greenflag and Stop, this set of controls could become rather cluttered. With that in mind we should make the interaction consistent across-platforms and have users delete blocks by dragging to the palette like in Scratch 2.0

**Comment by rachel-fenichel** [comment] 2016-12-12 22:41
Toggle-able by the Scratch user, or left in the codebase but not exposed in Scratch?

That is, in Scratch will there be a button to make the trash can appear and disappear?

**Comment by carljbowman** [comment] 2017-01-09 18:45
@rachel-fenichel - Sorry about that. Thanks for clarifying. The trash can should be 'left in the code but not exposed in Scratch'. No button in Scratch that will allow this change.

One odd behavior I have noticed about the animation: when the user drops the block on the palette, the block appears back over the workspace and then animates. The fact that the block appears back over the workspace, rather than remaining over the palette feels a bit awkward.

From Scratch GUI
![block deletion animation](https://cloud.githubusercontent.com/assets/3409578/21778563/e485a45c-d671-11e6-907f-94195b29150d.gif)

**Comment by rachel-fenichel** [comment] 2017-01-09 19:14
:+1: 

I think the deletion animation no longer does that in blockly--we can take a look after you pull in the last month or so of blockly updates.

**Comment by thisandagain** [comment] 2017-02-21 13:44
@carljbowman Do we need anything else here? I'm handling removal of the trashcan in the PR for https://github.com/llk/scratch-blocks/issues/43

**Comment by carljbowman** [comment] 2017-02-21 14:51
@thisandagain - We can close this case. 

The one issue that seems to be a regression and needs some more investigation is outlined here: https://github.com/LLK/scratch-blocks/issues/804

![current behavior mov](https://cloud.githubusercontent.com/assets/3409578/23169845/4442c6d4-f81b-11e6-9011-8827aeaad32d.gif)

We have inconsistent deletion behavior across GUI and VM.

**Closed as completed by carljbowman** 2017-02-21 14:51 UTC
Labels: design
