### ISSUE TITLE
Blocks 'getConnections_' function sometimes returns incorrect values

### ISSUE THREAD

**Issue by brassaro** [LLK/scratch-blocks#900] opened 2017-05-24 20:58 UTC
### Expected Behavior

When dragging a block around and holding it close to other blocks so that the connection preview shows, getConnections_ should return the same in all situations.

### Actual Behavior

When dragging a block around and holding it close to other blocks so that the connection preview shows, getConnections_ returns different values depending on the situations. An exception is thrown because the connection lists of blocks do not match, while they should actually be able to connect.

### Steps to Reproduce

Using vertical_playground.html, in the "tests" folder:
1. Drag a 1st block with a "next" connection from the flyout and place it at the top of the workspace;
2. Drag a 2nd block with a "previous" connection from the flyout and place it at the bottom of the workspace. Do not connect it to the first block;
3. Drag a 3rd block, with both "previous" and "next" connections, with no input, and place it on the workspace in the middle of the 2 previous blocks, without connecting any of them.
4. Drag a 4th block, with both "previous" and "next" connections, this time WITH an input, and place it on the workspace, connecting it to the 3rd block, before or after.
5. Start dragging the group of blocks composed of blocks 3 and 4.
6. Without releasing the blocks, drag the group so that the connection preview appears below the block placed at the top of the workspace (block 1).
7. Still without releasing the blocks, drag the group so that the connection preview above the block placed at the bottom of the workspace (block 2)
8. Notice the no connection preview is show, and that there is an exception thrown in the console: "Uncaught Connection lists did not match in length."

### Operating System and Browser

Mac OS 10.11.6
Chrome Version 58.0.3029.110 (64-bit)

**Comment by rachel-fenichel** [comment] 2017-05-24 21:22
Also probably mine.  

The error comes from [here](https://github.com/LLK/scratch-blocks/blob/develop/core/block.js#L667), which is being called from [here](https://github.com/LLK/scratch-blocks/blob/develop/core/insertion_marker_manager.js#L625).

**Comment by rachel-fenichel** [comment] 2017-05-24 22:42
@brassaro can I get a video/gif/screen capture of this?  I tried to replicate and didn't have any problems:
![22fbc4fe-2f3c-42bb-80aa-39ce443524e3](https://cloud.githubusercontent.com/assets/13686399/26428592/6d05f8ce-4097-11e7-993a-caa978b0e7c6.gif)

I think I'm replicating your test case correctly.  Let me know if I'm not.  And thanks for the detailed steps to reproduce it.

**Comment by brassaro** [comment] 2017-05-25 15:51
@rachel-fenichel mistake on my end: our project was not using scratch-blocks' most recent updates.
The bug I posted DOES NOT occur in latest versions. It was fixed with commit '6275e11' on May 22nd 2017 4:08pm.
Thanks for the quick reply!

**Comment by jwzimmer-zz** [comment] 2017-05-25 15:55
Closing since this bug no longer occurs, thanks @brassaro & @rachel-fenichel

**Closed as completed by jwzimmer-zz** 2017-05-25 15:55 UTC
