### ISSUE TITLE
variable reporter blocks load with different id, breaking comment connection

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-blocks#2003] opened 2019-10-08 21:13 UTC
### Expected Behavior

If you load a project with a comment attached to a variable reporter, the comment appears. 

### Actual Behavior

When you load the project the variable reporter has the wrong id, so the comment doesn't appear.

![VariableReporterBlockComment](https://user-images.githubusercontent.com/1088291/66433705-e5e52a00-e9ee-11e9-91d6-5a3e918e3f0f.gif)

### Steps to Reproduce

Create a project
Drag a `My Variable` reporter onto the workspace
Right click the reporter block and add a comment
Type something into the comment such as "this is a comment"
Save the project
Choose File>Download to your computer
Extract the project.json from the project and look at it
Note: The comment has a "blockId" that corresponds to the id of the variable reporter block
Back in the editor refresh the page
Note: the comment is not attached to the variable reporter block
Download the project a second time
Extract the project.json and open it
Note: the comment as the same "blockId" that it had before but the variable reporter has a different block ID

### Operating System and Browser

Mac Chrome

**Comment by BryceLTaylor** [comment] 2019-10-09 13:16
This was pointed out from the community in fresh desk ticket 183246.

**Comment by apple502j** [comment] 2020-07-21 17:10
Duplicate of LLK/scratch-vm#1893

**Comment by kchadha** [comment] 2022-03-24 20:55
closing as dupe of https://github.com/LLK/scratch-vm/issues/1893

**Closed as completed by kchadha** 2022-03-24 20:55 UTC
Labels: needs-triage
