### ISSUE TITLE
Following the instructions for  setup and build, scratch-blocks can not be build. 

### ISSUE THREAD

**Issue by thebravoman** [LLK/scratch-blocks#2863] opened 2022-09-23 20:47 UTC
### Expected Behavior

Successfully follow the instructions at https://github.com/LLK/scratch-blocks/wiki we should be able to start scratch-block

### Actual Behavior
```
$ npm install

> scratch-blocks@0.1.0 prepublish
> python build.py && webpack

Using remote compiler: closure-compiler.appspot.com ...

../closure-library/closure/bin/calcdeps.py
Error: Closure not found.  Read this:
  developers.google.com/blockly/guides/modify/web/closure

```

### Steps to Reproduce

Follow the instructions and on npm install the error above or a version of it appears.

### System Details
Ubuntu, 20.04

The main issue with the build is that it depends that there is a file called
```
../closure-library/closure/bin/calcdeps.py
```
Such file exists in closure-library repo from 11 years ago https://github.com/jarib/google-closure-library/tree/master/closure/bin

But the repo is no longer updated. It says
```
NO LONGER UPDATED - OFFICAL REPO MOVED TO GIT: https://github.com/google/closure-library
```

If we go to closure-library there is no longer this file calcdeps.py.

This means that following the wiki the project can not be build.

## Update 1
The scripts seem to be removed with the following commit in closure-library

```
commit 749634639af6b04bfe1d9d890bb037811e390b61
Author: Kelvin Jin <kelvinjin@google.com>
Date:   Mon Jun 21 13:32:12 2021 -0700

    RELNOTES: Delete open-sourced Python helper scripts.
    
    See https://github.com/google/closure-library/wiki/Migrating-off-Closure-Python-Scripts for information on migrating off of these scripts.
    
    PiperOrigin-RevId: 380652546
    Change-Id: I4ffcf7add875a2e4d5e0335236e567d4da4f5e6f

```

**Comment by cwillisf** [comment] 2022-10-06 15:52
I can't seem to reproduce exactly the issue you're seeing here, but it does look to me like remote compilation no longer works correctly. If I try to run `npm ci` or `npm install` in an up-to-date copy of `scratch-blocks` on Ubuntu 20.04 with Python 2.7 installed, I see this in the output:

```
> scratch-blocks@0.1.0 prepublish
> python build.py && webpack

Using remote compiler: closure-compiler.appspot.com ...

SUCCESS: blockly_uncompressed_vertical.js
SUCCESS: blockly_uncompressed_horizontal.js
FATAL ERROR
Required namespace "goog.events.EventWrapper" never defined.
??? at line 57:
goog.requireType('goog.events.EventWrapper');
^
```

There's a bunch of `npm`-related output before that, and `webpack`-related output after that, but that's the part where it goes wrong.

Are you performing some other steps before `npm install`? I'm curious why you see different results.

**Comment by benjiwheeler** [comment] 2022-10-11 14:13
@thebravoman, what version of npm are you using? It might be worth trying some other major versions, older and newer

**Comment by cwillisf** [comment] 2022-10-25 14:50
I plan to do some work related to problems with the "remote compile" mode, but I still can't reproduce the specific behavior called out in this issue. I'll close this for now; please let us know if you can provide more info!

**Closed as not planned by cwillisf** 2022-10-25 14:50 UTC

**Comment by thebravoman** [comment] 2022-11-08 14:47
Guess it is connected with https://github.com/LLK/scratch-blocks/pull/1964 where I again came to the closure not found. 
The combination of python2 and google-closure-compiler seems to bring up this issue. 
Node is 16.
Tried also with 17.
