### ISSUE TITLE
Comment top label is out of boundary when workspace comment was turn to display in the minimized.

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-blocks#2198] opened 2020-11-19 10:55 UTC
### Expected Behavior

Comment top bar label display normally.

### Actual Behavior

See the pictures as below:
![image](https://user-images.githubusercontent.com/15828392/99656046-6651d780-2a97-11eb-96cc-3e967d23b196.png)

"this.topBarLabel_" out of boundary when the comment language is Chinese. But is OK in Korean or English.

### Steps to Reproduce

- 1. Add a comment for workspace
![image](https://user-images.githubusercontent.com/15828392/99657035-964daa80-2a98-11eb-95c0-776592c4ddbb.png)

- 2. Typed some words in Chinese, like "啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊"
![image](https://user-images.githubusercontent.com/15828392/99657070-a36a9980-2a98-11eb-85be-7f9f276faa3e.png)

- 3. Turn the comment to minimize.
![image](https://user-images.githubusercontent.com/15828392/99657098-aa91a780-2a98-11eb-89d1-999c66fd01cb.png)

**Comment by BrightLin** [comment] 2020-11-19 12:18
I found a way to resolve. But it's not a good way.  We need slice more string for Chinese. Let's discuss

![image](https://user-images.githubusercontent.com/15828392/99665231-4d035800-2aa4-11eb-921b-21456b7da4a7.png)


```js
Blockly.WorkspaceComment.prototype.getLabelText = function() {
  if (this.content_.length > Blockly.WorkspaceComment.MAX_LABEL_LENGTH) {
    if (this.RTL) {
      return '\u2026' + this.content_.slice(0, Blockly.WorkspaceComment.MAX_LABEL_LENGTH);
    }
    var contentSliced = this.content_.slice(0, Blockly.WorkspaceComment.MAX_LABEL_LENGTH);
    var cnReg = /[\u3400-\u4DB5\u2F00-\u2FD5\u2E80-\u2EF3\uF900-\uFAD9\uE815-\uE86F\uE400-\uE5E8\uE600-\uE6CF\u31C0-\u31E3\u2FF0-\u2FFB\u3105-\u3120\u31A0-\u31BA\u4E00-\u9FCB]/g;
    if (cnReg.test(contentSliced) && contentSliced.match(cnReg).length > 7) {
      return contentSliced.slice(0, 7) + '\u2026';
    }
    return contentSliced + '\u2026';
  } else {
    return this.content_;
  }
};
```

**Comment by apple502j** [comment] 2020-11-19 12:21
Duplicate of #1680

**Comment by BryceLTaylor** [comment] 2020-11-19 19:41
Closing as duplicate of #1680

**Closed as completed by BryceLTaylor** 2020-11-19 19:41 UTC
