### ISSUE TITLE
Please fix it in Python 3.x

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-blocks#1940] opened 2019-05-21 05:23 UTC
### Expected Behavior

Install with Python 3.x.x

### Actual Behavior

It is only possible in Python 2.x.x

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by towerofnix** [comment] 2019-05-21 14:35
This is already being tracked issue #1679.

**Comment by Kenny2github** [comment] 2019-05-22 10:15
Duplicate of #1679

**Closed as completed** 2019-07-30 06:35 UTC
