### ISSUE TITLE
stop other scripts ... does not change target when the stage is selected

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#2056] opened 2020-04-01 12:45 UTC
The option `other scripts in sprite` in the stop block does not switch to `other scripts in stage` when the stage is selected. 

This has been known for a long time, but I didn't see an issue recording it, and it came up again with a translator.

**Comment by apple502j** [comment] 2020-04-01 14:42
Duplicate of LLK/scratch-gui#3543

**Comment by Kenny2github** [comment] 2020-04-01 16:54
Is this an issue with gui or blocks though?

**Comment by BryceLTaylor** [comment] 2020-04-27 18:15
I moved LLK/scratch-gui#3543 into Blocks and I'm going to close this one.

**Closed as completed by BryceLTaylor** 2020-04-27 18:15 UTC
