### ISSUE TITLE
Block stack layering - dragging a sub-stack into a stack doesn't bring it to the front

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#955] opened 2017-06-16 15:40 UTC
### Expected Behavior

If you have two stacks next to each other, and drag a long block into the leftmost stack, I would expect the stack you have most recently interacted with to be the top layer stack, but it is not.

### Actual Behavior

If you drop the stack you are dragging on top of another stack, the dragged block will be the top layer (over the other stack). But if you drop the stack you're dragging into the leftmost stack, the leftmost stack will be under the rightmost stack.

![out](https://user-images.githubusercontent.com/1320456/27233512-b17064b6-5287-11e7-8b2f-3f2d8abedc57.gif)

### Steps to Reproduce

- Drag out two stacks next to each other, but not overlapping
- Make a sub-stack that has a long block in it
- Drag that sub-stack into the leftmost stack, then left go (so it connects)
- Note the layering of the stacks

### Operating System and Browser

_Mac OS X El Capitan, Chrome 59_

**Comment by rachel-fenichel** [comment] 2017-06-17 14:27
Dupe of #937

**Closed as completed** 2017-06-22 14:51 UTC
