### ISSUE TITLE
Insertion marker eats boolean input

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-blocks#404] opened 2016-06-13 23:27 UTC
Everything freezes, and you can't complete the drag
![](http://i.cubeupload.com/2woM0u.png)

Steps to reproduce:
1. drag a boolean block from the flyout into the workspace
2. drag a block with a boolean input over the boolean block

**Comment by tmickel** [comment] 2016-06-13 23:46
Thanks for the report! I think this is a duplicate of https://github.com/LLK/scratch-blocks/issues/390

**Closed as completed by tmickel** 2016-06-13 23:46 UTC
