### ISSUE TITLE
No dropdown for number input in list blocks

### ISSUE THREAD

**Issue by ZenithRogue** [LLK/scratch-blocks#1467] opened 2018-04-23 14:30 UTC
List blocks do not have a dropdown option in the item selector. This prevents users from easily using "last" and "random". However, they still appear to work if you use the join block to enter the text.

**Comment by Kenny2github** [comment] 2018-04-24 02:35
I recall there being an issue where @thisandagain said that 3.0 would be moving away from number/dropdown hybrids - is that still the case?

**Comment by apple502j** [comment] 2018-04-24 07:55
_I don't care even if it's dupe of #1335_

Then compatibility problem would happen

**Comment by ZenithRogue** [comment] 2018-04-24 12:08
@apple502j wow, I didn't notice. I even commented on it last time it was brought up.

**Comment by thisandagain** [comment] 2018-04-24 12:34
Tracking in https://github.com/LLK/scratch-blocks/issues/1335

**Comment by thisandagain** [comment] 2018-04-24 12:34
I knew this was tracked somewhere else. Thanks @apple502j

**Closed as completed by thisandagain** 2018-04-24 12:34 UTC
Labels: feature, needs-triage
