### ISSUE TITLE
Implement "Go To Definition" context menu option

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1312] opened 2017-12-20 15:36 UTC
As per feature in Scratch 2.0:
![untitled](https://user-images.githubusercontent.com/747641/34214843-a4967e42-e571-11e7-8e5b-725249e8da7b.gif)

**Comment by thisandagain** [comment] 2017-12-20 15:40
For reference:
https://github.com/LLK/scratch-blocks/pull/1311/files

**Comment by rachel-fenichel** [comment] 2017-12-20 18:03
Dupe of https://github.com/LLK/scratch-blocks/issues/1136

**Closed as completed by rachel-fenichel** 2017-12-20 18:03 UTC
Labels: feature, help wanted
