### ISSUE TITLE
error during executing build.py

### ISSUE THREAD

**Issue by rohinipatare** [LLK/scratch-blocks#1590] opened 2018-06-15 04:41 UTC
### Expected Behavior
All the modules should successfully executed.

### Actual Behavior
error during running python file
  #python build.py
Traceback (most recent call last):
  File "build.py", line 598, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

### Operating System and Browser

Ubuntu 15.10 & Mozilla Firefox Browser

**Comment by regcole** [comment] 2018-06-18 01:28
I'm getting the same error on Windows 10. It happens with Windows 10 console and with the Ubuntu WSDL. The script does work when I run it on Mac OS X though.

**Comment by thisandagain** [comment] 2018-06-20 18:44
Hmm. @regcole are you getting the same error when using WSDL? That stack trace isn't very helpful so any more information would be great.

**Comment by regcole** [comment] 2018-06-20 18:55
@thisandagain  Yes I am getting the error with WSDL. The error can be  tested/reproduced on my machine with effective code of 
```
CLOSURE_COMPILER_NPM = "google-closure-compiler"
closure_compiler = CLOSURE_COMPILER_NPM
test_args = [closure_compiler, os.path.join("build", "test_input.js")]
test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

**Comment by thisandagain** [comment] 2018-06-20 18:57
@cwillisf @fsih Could you folks please attempt to repro when you have a moment?

**Comment by cwillisf** [comment] 2018-06-21 16:53
I see this same error if I run `python build.py` from the command line. However, it works correctly if I let `npm` run it for me. Specifically, I can use `npm install` or `npm run prepublish` to build successfully.

@thisandagain do you think we should update the [instructions on the wiki](https://github.com/LLK/scratch-blocks/wiki#building) to suggest using `npm` instead of running `python build.py` directly? In addition to the issue discussed here, the wiki instructions don't mention running `webpack` -- which is handled by `npm i` or `npm run prepublish`.

**Comment by thisandagain** [comment] 2018-06-21 20:00
@cwillisf Updating the instructions in the wiki sounds like a great idea. @regcole and @rohinipatare can you please confirm that this works for you as well?

**Comment by cwillisf** [comment] 2018-06-26 19:13
I've updated the instructions on the wiki -- basically rewriting the first half of [the "Building" section](https://github.com/LLK/scratch-blocks/wiki#building).

@thisandagain could you give that a quick eyeball?

@regcole and @rohinipatare, I believe the updated instructions will solve the issues you're seeing. Please give them a try and let us know what you see, so we can either close this issue or continue investigating. Thanks!

**Comment by thisandagain** [comment] 2018-06-26 19:31
Looks good @cwillisf! Thanks.

**Closed as completed by thisandagain** 2018-06-26 19:31 UTC
Labels: ergonomics, question, help wanted

**Comment by lishuai199502** [comment] 2018-07-02 15:05
@cwillisf could you please say what is you Operating System?i have trie npm run prepublish,and it failed,both on centos7 and win10

**Comment by jyh129143** [comment] 2018-07-03 03:04
unfortunately,your updated instructions in the wiki 

doesn't work well with me,actually it will run into an error like:
![image](https://user-images.githubusercontent.com/29747808/42196509-e11acc14-7eb0-11e8-963f-fd10410cd31e.png)

**Comment by lishuai199502** [comment] 2018-07-05 13:04
@jyh129143 me too.

**Comment by rohinipatare** [comment] 2018-07-06 04:48
for me It executed successfully with command npm run prepublish instead of python build.py

**Comment by jyh129143** [comment] 2018-07-06 06:40
@rohinipatare could please relate your procedure of successfully run since git clone? And your npm/OS/python -v?

**Comment by rohinipatare** [comment] 2018-07-06 07:37
@jyh129143 I followed all the same procedure which are in wiki, I am getting error at last step i.e during executing python file build.py. I was executing it by command **python build.py** directly which was giving error and terminatin. To build it successfully, I only use command **npm run prepublish** in place of **python build.py** inside the respective directory. 
I am using 
npm 5.5.1, Fedora OS and Pytyhon 2.7.13

**Comment by lishuai199502** [comment] 2018-07-07 11:38
i tried it mac os,it succeed.but failed on windows10 and centos7

**Comment by jyh129143** [comment] 2018-07-09 01:14
Aha,it sounds mysterious.Could you please show me how you operated and you version of npm & python?

**Comment by Woondal** [comment] 2018-07-10 09:09
@jyh129143 I'm getting same error too... (npm 6.1.0, Window10 x64, Python 2.7.15)

**Comment by fatpandaria** [comment] 2018-07-16 15:03
looks like many people are stucked here,(node -v9.7.1,npm -v5.6.0,Windows 10x64,Python2.7.10),could anyone help us?
same error as: File "build.py", line 598, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
Still not working although I add shell = True in line 595.

**Comment by jyh129143** [comment] 2018-07-24 03:11
@rohinipatare @lishuai199502 does it convinient for you to share a screenshot of successful building?

**Comment by pawelmisk** [comment] 2018-09-18 21:33
For anyone interested I have a workaround to this problem. Simply modify build.py in a text editor and add OSError to the handled exception list. The build should now succeed using the online closure compiler.

`603:   except (**OSError**, ImportError, AssertionError):`

The puzzling thing about the build script is that it tries to execute "google-closure-compiler" in the build directory which would require some work to setup. The advanced compiler steps outlined in the blockly docs [here](https://developers.google.com/blockly/guides/modify/web/advanced) didn't resolve this problem so maybe something got lost in translation.

Anyways, assuming you have correctly installed the required deps (python27 + java) then you can comment out the dubious check on lines 598-601 of build.py and you should be alright for a local build.

```
598:    # test_args = [closure_compiler, os.path.join("build", "test_input.js")]
598:    # test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
598:    # (stdout, _) = test_proc.communicate()
598:    # assert stdout == read(os.path.join("build", "test_expect.js"))
```

**Comment by upupli** [comment] 2018-11-03 07:13
I have the same trouble,anyone solved it ?

**Comment by zptmxj** [comment] 2018-11-08 01:55
me too.

**Comment by hpgood** [comment] 2019-03-29 11:20
in windows 10,change all "google-closure-compiler" to "google-closure-compiler.cmd"
that will solve it,but have other problem,
the cmd args is too long.（命令行太长）

**Comment by kowaihasue** [comment] 2019-04-15 07:22
i've tried your solution but still get an error with no error detail.. (on windows 10)

> For anyone interested I have a workaround to this problem. Simply modify build.py in a text editor and add OSError to the handled exception list. The build should now succeed using the online closure compiler.
> 
> `603: except (**OSError**, ImportError, AssertionError):`
> 
> The puzzling thing about the build script is that it tries to execute "google-closure-compiler" in the build directory which would require some work to setup. The advanced compiler steps outlined in the blockly docs [here](https://developers.google.com/blockly/guides/modify/web/advanced) didn't resolve this problem so maybe something got lost in translation.
> 
> Anyways, assuming you have correctly installed the required deps (python27 + java) then you can comment out the dubious check on lines 598-601 of build.py and you should be alright for a local build.
> 
> ```
> 598:    # test_args = [closure_compiler, os.path.join("build", "test_input.js")]
> 598:    # test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
> 598:    # (stdout, _) = test_proc.communicate()
> 598:    # assert stdout == read(os.path.join("build", "test_expect.js"))
> ```

**Comment by JiangLiruii** [comment] 2019-05-08 01:47
> in windows 10,change all "google-closure-compiler" to "google-closure-compiler.cmd"
> that will solve it,but have other problem,
> the cmd args is too long.（命令行太长）

Got the same problem

**Comment by nogarcia** [comment] 2019-08-18 02:31
Using @pawelmisk 's workaround and then getting the closure library does work for me.

**Comment by sxcem** [comment] 2019-10-03 09:15
the cmd args is too long, try it: https://blog.csdn.net/weixin_42856280/article/details/90288065

I test win10,  tks everyone!

**Comment by Salik-Rafiq** [comment] 2020-06-19 16:29
I could not get this to work locally on Windows with the Windows Compiler. I think it might be the way that I had npm install the google-closure stuff.
I put this at the same level as the other scratch repository folders. 

So I had:
closure-library/
&nbsp;&nbsp;&nbsp;node-modules/
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; google-closure-library
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;google-closure-compiler
scratch-blocks/
 &nbsp;&nbsp;&nbsp;node-modules/
  &nbsp;&nbsp;&nbsp;&hellip;


In the end I commented out the local compile attempt which kept throwing an exception which wasn't handled (File Not Found)
and modified the line at 589 to be:
`      calcdeps = import_path(os.path.join(
          closure_root, closure_library, CLOSURE_DIR_NPM, CLOSURE_LIBRARY_NPM, "closure", "bin", "calcdeps.py"))
`
I think the line 574 expects the compiler to be in your path - if it isn't I'll have to change it to add in the path to the compiler myself.

which got the remote compile started...it does take it's time and as I write this 15 minutes and it's still going. 

Not the friendliest setup - has taken hours to get it to this point.

How long does it take to "compile" anyway because I'm wondering if it's failed.
