### ISSUE TITLE
Drag bugs related to merge

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#512] opened 2016-07-12 15:28 UTC
@rachel-fenichel 
What I've found so far:
- [x] When creating a new block from the flyout, the block disappears for a moment (until the mouse cursor moves).
- [x] Snapping two blocks together causes the stack to jump
- [x] Dragging sometimes causes this error:

> block_svg.js:198 Uncaught TypeError: Cannot read property 'id' of null

**Comment by tmickel** [comment] 2016-07-12 15:29
Sometimes I am able to trigger this error when creating a block from the flyout:

> flyout.js:970 Uncaught TypeError: Cannot read property 'contentHeight' of null

More and more of these errors accumulate as I move the mouse.

**Comment by tmickel** [comment] 2016-07-12 15:30
^ During the above error, the block is invisible until dropped.

**Comment by tmickel** [comment] 2016-07-12 15:33
Note: snapping statement blocks appears to move the stack downward; snapping in a value block appears to move the stack upward...

**Comment by tmickel** [comment] 2016-07-12 16:49
- Angle picker is broken

**Comment by rachel-fenichel** [comment] 2016-07-12 21:44
"Cannot read property 'id' of null" was due to a failure to correctly dispose of connections, meaning that the block would try to bump deleted blocks whose connections were still in the database.  This was due to accidential deletion of one line.
https://github.com/LLK/scratch-blocks/pull/510/files#diff-5148dfb78f1d110be97f1d3539fa647cL260

**Comment by rachel-fenichel** [comment] 2016-07-12 22:13
I think fixing connection disposal also fixes " snapping statement blocks appears to move the stack downward; snapping in a value block appears to move the stack upward" and "Snapping two blocks together causes the stack to jump".

**Comment by rachel-fenichel** [comment] 2016-07-12 22:19
What's broken on the angle picker?  I can't get it to show up.  Is that the brokenness?

**Comment by rachel-fenichel** [comment] 2016-07-12 22:35
"When creating a new block from the flyout, the block disappears for a moment (until the mouse cursor moves)." was caused by not distinguishing between autoclosing flyouts and always open flyouts.  Also fixed in #514.

**Comment by tmickel** [comment] 2016-07-13 17:08
The angle picker only comes up in the "point in direction" block (the only one, I think, that we have to set an absolute angle).

The error is:
`field_angle.js:215 Uncaught TypeError: Blockly.FieldAngle.angleValidator is not a function`
I can probably investigate...

**Closed as completed** 2016-07-13 18:29 UTC
