### ISSUE TITLE
On mobile, FlyoutButton click only recognized when button text is tapped

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#1205] opened 2017-11-02 18:17 UTC
### Expected Behavior

On mobile, upon tapping inside button border but not tapping on text, button click is recognized.

### Actual Behavior

On mobile, tapping inside the button border on the empty space within the button is not recognized as a click.

### Steps to Reproduce

1. Load vertical_playground.html.
2. From Google Chrome menu, select View > Developer > Developer Tools and then select a device of your choice (e.g. iPad Pro).
3. Select Data category so that "Create Variable" button is visible in the flyout.
4. Tap inside the "Create Variable" button without tapping on the button text. For instance, tap between the left edge of the button and the start of the text, or tap between the end of the text and the right edge of the button.

Workaround: Tap the button text, and the button will be clicked.

Note: This issue doesn't happen on desktop (or when Developer Tools are not used).

### Operating System and Browser

Mac OS 10.11.6 Google Chrome 62.0.3202.62

**Comment by mrjacobbloom** [comment] 2017-11-04 00:48
Possible duplicate of #941 and #1073

**Comment by thisandagain** [comment] 2017-12-20 17:57
Tracking in #941

**Closed as completed by thisandagain** 2017-12-20 17:57 UTC
Labels: help wanted
