### ISSUE TITLE
Performance - Dragging a block from the flyout to the workspace

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#835] opened 2017-03-09 22:52 UTC
### Expected Behavior

Dragging a block from the flyout to the workspace should be smooth.

### Actual Behavior

Dragging a block from the flyout to the workspace results in a noticeable hitch that is fairly pronounced in the profiler.

**Comment by picklesrus** [comment] 2017-03-16 18:27
No solutions yet, but it seems we've somehow made the composite layers phase take a very long time. I haven't optimized composite layers before, so I'll need to do some research to understand this fully.

Blockly's  performance degraded similarly. I did some comparisons with blockly's master and develop branches and found that we've made composite layers increase from .21ms to 41ms.

Scratch-blocks appears to have the same problem, although composite layers is broken into two expensive passes instead of 1.  The composite layers in the following screen shot measure ~21ms and ~13ms.
Zoomed out view of dragging a block from the toolbox:
![screen shot 2017-03-16 at 10 48 16 am](https://cloud.githubusercontent.com/assets/15675877/24010877/4e1f302a-0a36-11e7-8bec-011f6d109c43.png)

There are also a bunch of calls to getComputedTextLength when a block is created that cause a recalculate style.  As far as I can tell these were there when we were happy with the performance.  However, I suspect some optimization could be done with field width caching, especially since we're making a duplicate of an already rendered block.  The code isn't setup to make this trivial, but I imagine we could steal the cached text calculation values from the flyout block and pre-populate the cache in the new one. 
Most of the little red flags in the following are from calculating text size.
![screen shot 2017-03-16 at 10 46 55 am](https://cloud.githubusercontent.com/assets/15675877/24010924/7cb2408a-0a36-11e7-81dd-25599115f4e6.png)

**Comment by picklesrus** [comment] 2017-03-17 23:48
I think the cursor causes the large composite layer times as it makes the following transitions during a drag out of the toolbox:
1. closed hand as you mouse down
2. hand with X (since the block is still over the toolbox)
3. closed hand as you cross the toolbox boundary

I haven't wrapped my head around what causes composite layers ... but deleting the entirety of setCursor in css.js does make them go away... The cursor has been on my performance suspect list for a while since it is set by changing the stylesheet.  Perhaps it is now more visible because of the other performance work?

There's definitely some more investigation to do before I know how to fix this.  I'm no longer confident that this happened recently. I originally thought it wasn't present in blockly's master branch, but it is.

If the goal is to put this in front of people on mobile devices, one quick hacky thing to do is to guard the code in setCursor with a user agent check.

**Comment by thisandagain** [comment] 2017-03-18 21:28
Thanks for the update @picklesrus ! 😄

**Comment by picklesrus** [comment] 2017-04-20 17:58
Sent out a PR for this upstream. See https://github.com/google/blockly/pull/1057 and context on solution here: https://github.com/google/blockly/issues/981

Once it is in, we can figure out if you want me to apply it to scratch-blocks for wait for the next merge.

**Comment by rschamp** [comment] 2017-05-31 17:45
@picklesrus Did the fix for this come in with the last merge?

**Comment by picklesrus** [comment] 2017-06-05 14:20
I think 2 merges ago?  IIRC, it was part of the merge finished the week after scratch day. I haven't verified the perf changes in scratch-blocks though. Are you still noticing that things are slow?

**Comment by rschamp** [comment] 2017-06-08 15:16
It looks fixed to me, @thisandagain please re-open if you disagree.

**Closed as completed by rschamp** 2017-06-08 15:16 UTC
