### ISSUE TITLE
"When timer > x" block does not activate script when it is clicked

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#845] opened 2017-03-15 20:45 UTC
### Expected Behavior

In 2.0, clicking a stack with "When timer greater than 0" as the hat block activates the stack.

### Actual Behavior

In 3.0, clicking a stack with "When timer greater than 0" as the hat block does not activate the stack.
The stack will be activated on green flag (when timer conditional is true).

### Steps to Reproduce

- Compare behaviour in 2.0 & 3.0
- Put "when timer greater than x" block in the scripting area
- Change x to 0
- Add the stamp block to the stack
- Put  "when this sprite clicked" block in the scripting area
- Add the stamp block to that stack
- Click on each stack, then drag the sprite to see if the stamp occurred
- Note the stamp occurred for the "when this sprite clicked" stack but not for the "when timer > 0" stack
- Delete the "when this sprite clicked" stack
- Press green flag
- Note that the stamp does occur for the "when timer > 0" block

### Operating System and Browser

_Mac El Capitan, Chrome 56_

**Comment by neurosie** [comment] 2017-05-24 02:15
It looks like this is caused because the greater than hats are [edge-activated](https://github.com/LLK/scratch-vm/blob/develop/src/engine/runtime.js#L679), so they already have a thread running when the stack click tries to [toggle them](https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js#L197).

**Comment by carljbowman** [comment] 2017-06-22 14:55
This is a dupe of https://github.com/LLK/scratch-vm/issues/153

**Comment by fsih** [comment] 2017-07-12 15:26
There are 2 issues contributing here
- The one found by neurosie, where clicking on the stack toggles the script, and since the script is running every frame, toggling it which should turn it on turns it off
- The one mentioned by Tim in LLK/scratch-vm#153 , where we don't run the code under the hat block because it's a "when" block, which guards that it's only supposed to run once, when the boolean expression goes from false to true

**Closed as completed** 2017-08-03 21:38 UTC
Labels: help wanted
