### ISSUE TITLE
Console print error when scrollbars is set to false

### ISSUE THREAD

**Issue by Ryuurock** [LLK/scratch-blocks#2015] opened 2019-11-19 08:02 UTC
### Expected Behavior

Console no error.

### Actual Behavior

Console print error when scrollbars is set to false

### Steps to Reproduce

scrollbars set to false

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment] 2019-11-19 08:14
Duplicate of #2016

**Closed as completed** 2019-11-19 09:28 UTC
