### ISSUE TITLE
ctrl-c bug

### ISSUE THREAD

**Issue by wwj718** [LLK/scratch-blocks#1440] opened 2018-04-12 14:01 UTC
### Expected Behavior

choose a block then press Ctrl+c，then nothing will happen

### Actual Behavior

choose a block then press Ctrl+c， This will happen:

![image](https://user-images.githubusercontent.com/3153878/38682085-cd29fc88-3e9c-11e8-8d87-34b03733e35a.png)

I can not move it or delete it

### Operating System and Browser

Mac OS 10.12 chrome 65.0.3325.181

**Comment by mrjacobbloom** [comment] 2018-04-12 15:14
This sounds like a duplicate of #1373

**Comment by rachel-fenichel** [comment] 2018-04-12 16:57
Dupe, and fixed upstream.

**Closed as completed by rachel-fenichel** 2018-04-12 16:57 UTC
