### ISSUE TITLE
Drag performance degrades when ghosts/insertion markers are being created/removed

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#200] opened 2016-04-11 21:55 UTC
@picklesrus @rachel-fenichel 

On my device it seems like drag performance suffers a lot when we're adding/removing ghosts - i.e., dragging on top of blocks, things get very slow.

How could we improve this?
-Is the whole stack being re-rendered, could we avoid re-rendering most of the blocks (I guess except parent blocks, in case we need to stretch a pants?
-Is it the rendering of the ghost block itself, in which case could we cache this?
-Is it just a timing issue, in which case could we fix it by using requestAnimationFrame to update the drag position and/or draw the ghosts?

**Comment by thisandagain** [comment] 2016-06-24 18:44
Depends on #154

**Comment by picklesrus** [comment] 2016-07-28 18:39
I'm taking a look at this independent of #154 for now since there seem to be some improvements I can make that are independent of the workspace drag.  For reference, here is a screenshot of a timeline I took where I dragged a single block along a stack.  It is quite clear where the insertion markers show up/disappear on the top portion of that image and the bottom portion is one of those zoomed in. 
![screen shot 2016-07-28 at 11 37 36 am](https://cloud.githubusercontent.com/assets/15675877/17224944/e1feeaea-54b7-11e6-993b-d554e7563ea0.png)

**Comment by tmickel** [comment] 2016-07-28 20:49
@picklesrus Do you think improvements purely here could bring us under frame budget? It was my impression that the improvements in #154 caused this to slow down even more (more painting)? Ofc it does look like a lot of time is being spend in the screen CTM...

**Comment by picklesrus** [comment] 2016-07-28 23:24
For dragging blocks around? Maybe.  The timeline above is without #154.  The version with #154 looks similar. The problem is really the repeated calls to render which in turn call getScreenCTM.  I need to look into the reason updateInverseScreenCTM keeps getting called.  I don't believe we should have to call it that often.

**Comment by tmickel** [comment] 2016-07-28 23:26
Oh, ok, cool! I had assumed that the version with #154 looked substantially different, but I haven't done as much investigation as you have. Cool, that's encouraging :)

**Comment by picklesrus** [comment] 2017-01-05 00:48
I dug into this again today and realized the we fixed main offender mentioned earlier by caching the result of getScreenCTM.  The blockly commit was https://github.com/google/blockly/commit/c4cad3c6e4d4e3fac0e68a7c49e5f820152794ed.

![screen shot 2017-01-04 at 4 33 56 pm](https://cloud.githubusercontent.com/assets/15675877/21664533/f8118d62-d29b-11e6-97d6-9ac5030a8f4b.png)
Attaching a screenshot of the timeline captured today, you can see all of the red triangles are gone and the javascript execution is down to ~6ms.  There is still the recalculate style, layout, and paint to consider in the frame budget, but it is, at least on my macbook air, a "green" frame in chrome. The repaint area is also pretty minimal now - only the stack of blocks that is changing rather than the entire workspace.

I also looked at the frame rate while dragging a block into a stack running a  small animation on https://llk.github.io/scratch-vm/ and it feels much less janky than I remember.

There isn't any immediately obvious low hanging fruit here anymore.  I believe more improvements would involve significant changes to how we handle shifting blocks when a new block (or stack) is inserted.  Currently, I don't think the amount of work required is worth any improvements we could squeeze out (probably only a few more ms.)

**Comment by thisandagain** [comment] 2017-01-05 14:22
@picklesrus Thanks for the update! Based on this I think we could close this for now and re-open should it continue to be an issue in the future.

**Closed as completed by thisandagain** 2017-01-05 14:22 UTC
Labels: enhancement, performance
